#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects that it lives two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/../.." && pwd )"

go get -t -v -d ./...

pushd ${BASE_DIR}
    go build -v
    go install github.com/onsi/ginkgo/ginkgo

    ginkgo -p -r -race -failOnPending -randomizeAllSpecs ./integration_test
popd
